// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oepwmwwykdqiszzaietf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lcHdtd3d5a2RxaXN6emFpZXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMjY3ODYsImV4cCI6MjA4NDYwMjc4Nn0.el1TnWxmxxZHJwwfCwD6Tvbx-K8OZ7f2yw7orDksSdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);